### PR TITLE
(chore) add rockspec for luarocks

### PR DESCRIPTION
**Pull request by vinayakhulawale**
Adds rockspec so this library can be published to luarocks from correct repo

### CODE REVIEW

**Comment by spacewander** [comment]
I got `Error: /path/to/lua-resty-rsa/lua-resty-rsa-0.06-dev.rockspec: Type mismatch on field version: invalid value 0.06-dev does not match '[%w.]+-[%d]+'` when I tried to build the spec.

If you want to install the latest version always, you may need to use `dev-1` as the version number, like https://github.com/mpeterv/luacheck/blob/master/luacheck-dev-1.rockspec?

BTW, I found someone has published lua-resty-rsa (in their namespace) just now: https://luarocks.org/modules/p0pr0ck5/lua-resty-rsa. Quite interesting.

**Comment by vinayakhulawale** [comment]
should I change it to `0.05-1` so you can publish it with `0.05` version ?

**Comment by spacewander** [comment]
I am sorry that I can't publish lua-resty-rsa to luarocks, as the package name `lua-resty-rsa` is already taken by https://luarocks.org/modules/p0pr0ck5/lua-resty-rsa. I don't like an alternative name like `lua-resty-rsa-from-spacewander`, which is ridiculous.

Anyway, I will merge this PR, so that you could build the rock in your machine. Could you squash the commits?

**Comment by vinayakhulawale** [comment]
@spacewander - done. I will try contacting @p0pr0ck5 to check if he can publish latest version in luarocks repo.

**Comment by p0pr0ck5** [comment]
I’ll be happy to remove my rockspec so the “correct” one can be added, but I’d like to coordinate that with whoever will push it up to avoid downtime.

**Comment by vinayakhulawale** [comment]
thanks @p0pr0ck5 ! @spacewander would you be able to co-ordinate with @p0pr0ck5 ? As long as latest version gets uploaded to luarocks whenever it gets released, it's all good !

**Comment by spacewander** [comment]
@p0pr0ck5 @vinayakhulawale 
Once the `lua-resty-rsa` is removed, I will submit the rock to take over the name.

@p0pr0ck5 
When will you have free time next week (in UTC time)? I can pick up a time interval to do the switch.

**Pull request merged**
